In [1]:
import numpy as np
from sklearn import preprocessing


In [11]:
X = np.array([[ 1., 15000.,  250.],
              [ 2.,  16000.,  100.],
              [ 0.,  20000., 200.]])


In [12]:
X_scaled = preprocessing.scale(X)
X_scaled


array([[ 0.        , -0.9258201 ,  1.06904497],
       [ 1.22474487, -0.46291005, -1.33630621],
       [-1.22474487,  1.38873015,  0.26726124]])

In [13]:
X_scaled.mean(axis = 0)


array([ 0.00000000e+00,  0.00000000e+00, -1.66533454e-16])

In [16]:
X_scaled.std(axis= 0)


array([1., 1., 1.])

In [17]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)


array([[ 0.        , -0.9258201 ,  1.06904497],
       [ 1.22474487, -0.46291005, -1.33630621],
       [-1.22474487,  1.38873015,  0.26726124]])

In [18]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        , -7.86900794, -2.93987366]])